[package]
name = "rogan"
version = "0.1.0-pre"
authors = ["Marshall Bockrath-Vandegrift <llasram@gmail.com>"]

[dependencies]
hyper = "0.7"
serde = "0.6"
serde_json = "0.6"
serde_macros = "0.6"
chrono = "0.2"
websocket = "0.14"
